### ISSUE TITLE
Hw5

### ISSUE THREAD

**Issue by utkarsh0902311047** [pai4451/ML2021#1]
Hi,
Thank you for providing the back translation code.
What are those assertion errors mentioned in your HW5 code?

Regards
Utkarsh

**Comment by pai4451** [comment]
You can safely ignore that. I ran my code on Colab without issue.

**Comment by utkarsh0902311047** [comment]
I am running it on Kaggle, and after 12 hours, it was canceled. How much time does it take you to finish?
Can you suggest some way, please?

**Comment by pai4451** [comment]
In my implementation, it might take more than 24 hours. Having your own computing resource is a way to do so.
