### ISSUE TITLE
HW7 Out of memory

### ISSUE THREAD

**Issue by Ponytai1j** [pai4451/ML2021#2]
When i run the HW7 TA example code, my cpu ram keep increasing until out of my 64G ram.I think this problem is coming from the training process. 
`train_loss += output.loss` # store the complete compution graph leading to out of memory
`train_loss += output.loss.detach() or .item()` if i modify original code to this, problem solved.

So, my question is, didnt you come across this problem? If not, why this happened to me, but TA and your code works well.
Just assume TAs example code should not be wrong, so afraid of myself may ignore something important.
Really hope you can help me, thanks in advance.

**Comment by pai4451** [comment]
`Tensor.detach()`  detached tensor from the current graph. This helps prevent memory leak.
